QUESTION 1

In [11]:
with open("supermarket_sales - Sheet1.csv","r") as f:
    # Read the column names
    headers = f.readline().strip().split(",")

    # store the values as dictionaries
    transactions = []

    for line in f:
        values = line.strip().split(",")
        records = dict(zip(headers, values))
        transactions.append(records)
# print the first 3 records
for record in transactions[:3]:
    print(record)

# print the sum of all the transactions
print("Print all the transactions: ", len(transactions))

#  print all columns names
print(headers)
    

{'Invoice ID': '750-67-8428', 'Branch': 'A', 'City': 'Yangon', 'Customer type': 'Member', 'Gender': 'Female', 'Product line': 'Health and beauty', 'Unit price': '74.69', 'Quantity': '7', 'Tax 5%': '26.1415', 'Total': '548.9715', 'Date': '1/5/2019', 'Time': '13:08', 'Payment': 'Ewallet', 'cogs': '522.83', 'gross margin percentage': '4.761904762', 'gross income': '26.1415', 'Rating': '9.1'}
{'Invoice ID': '226-31-3081', 'Branch': 'C', 'City': 'Naypyitaw', 'Customer type': 'Normal', 'Gender': 'Female', 'Product line': 'Electronic accessories', 'Unit price': '15.28', 'Quantity': '5', 'Tax 5%': '3.82', 'Total': '80.22', 'Date': '3/8/2019', 'Time': '10:29', 'Payment': 'Cash', 'cogs': '76.4', 'gross margin percentage': '4.761904762', 'gross income': '3.82', 'Rating': '9.6'}
{'Invoice ID': '631-41-3108', 'Branch': 'A', 'City': 'Yangon', 'Customer type': 'Normal', 'Gender': 'Male', 'Product line': 'Home and lifestyle', 'Unit price': '46.33', 'Quantity': '7', 'Tax 5%': '16.2155', 'Total': '340.5

QUESTION 2: 
Using the data you loaded in Question 1 and only built-in Python, answer the following:
a) What are the unique branches in the dataset? Store them in a suitable data structure and
print them.
b) How many unique product lines does the dataset contain? Print the number.
c) Build a dictionary where each key is a branch name and the value is a list of all Total
amounts recorded for that branch. Print the number of transactions in each branch.

In [28]:
# a
branch = set()
for transaction in transactions:
    branch.add(transaction["Branch"])
print(branch)
# b
product_lines = set()
for transaction in transactions:
    product_lines.add(transaction["Product line"])
print(len(product_lines))
# c
branch_totals = {}

branches = [transaction["Branch"] for transaction in transactions]
totals = [float(transaction["Total"]) for transaction in transactions]

# Combine branches and totals
data = dict(zip(branches, totals))


for branch in data:
    print(branch, ":", data[branch], "transactions")

{'A', 'B', 'C'}
6
A : 649.299 transactions
C : 42.3675 transactions
B : 1022.49 transactions


QUESTION 3:

Create a separate Python file called sales_utils.py that contains a function named
count_by_group. The function should take two arguments: a list of dictionaries and a column
name. It should return a dictionary showing how many transactions exist for each unique value
of that column. Import the function into your notebook and use it to count transactions by
Branch and by Payment method. Print both results.

QUESTION 4: 

Load the dataset using Pandas. Extract the Unit price, Quantity, Total, and Rating columns as
NumPy arrays. Name them unit_price_arr, quantity_arr, total_arr, and rating_arr respectively.
For each array, print its shape, data type, minimum value, maximum value, and first 5 elements.

In [3]:
import numpy as np
import pandas as pd
sales = pd.read_csv("supermarket_sales - Sheet1.csv")
unit_price = np.array(sales["Unit price"])
quantity_arr = np.array(sales["Quantity"])
total_arr = np.array(sales["Total"])
rating_arr = np.array(sales["Rating"])
# unit_price
print(unit_price.shape)
print(type(unit_price))
print(unit_price.min())
print(unit_price.max())
print(unit_price[:5])
# quantity_price
print(quantity_arr.shape)
print(type(quantity_arr))
print(quantity_arr.min())
print(quantity_arr.max())
print(quantity_arr[:5])
# total_arr
print(total_arr.shape)
print(type(total_arr))
print(total_arr.min())
print(total_arr.max())
print(total_arr[:5])
# rating_arr
print(rating_arr.shape)
print(type(rating_arr))
print(rating_arr.min())
print(rating_arr.max())
print(rating_arr[:5])

(1000,)
<class 'numpy.ndarray'>
10.08
99.96
[74.69 15.28 46.33 58.22 86.31]
(1000,)
<class 'numpy.ndarray'>
1
10
[7 5 7 8 7]
(1000,)
<class 'numpy.ndarray'>
10.6785
1042.65
[548.9715  80.22   340.5255 489.048  634.3785]
(1000,)
<class 'numpy.ndarray'>
4.0
10.0
[9.1 9.6 7.4 8.4 5.3]


QUESITON 5

Using NumPy functions only, compute the following statistics for total_arr and for rating_arr.
Print all results neatly formatted to 2 decimal places.
a) Mean, median, and standard deviation.
b) Minimum and maximum values.
c) The value at the 25th percentile and the value at the 75th percentile.

In [4]:
total_arr = np.array(sales["Total"])
rating_arr = np.array(sales["Rating"])

import numpy as np

# Statistics for Total
print("TOTAL STATISTICS")
print("Mean:", format(np.mean(total_arr), ".2f"))
print("Median:", format(np.median(total_arr), ".2f"))
print("Standard Deviation:", format(np.std(total_arr), ".2f"))
print("Minimum:", format(np.min(total_arr), ".2f"))
print("Maximum:", format(np.max(total_arr), ".2f"))
print("25th Percentile:", format(np.percentile(total_arr, 25), ".2f"))
print("75th Percentile:", format(np.percentile(total_arr, 75), ".2f"))

print()

# Statistics for Rating
print("RATING STATISTICS")
print("Mean:", format(np.mean(rating_arr), ".2f"))
print("Median:", format(np.median(rating_arr), ".2f"))
print("Standard Deviation:", format(np.std(rating_arr), ".2f"))
print("Minimum:", format(np.min(rating_arr), ".2f"))
print("Maximum:", format(np.max(rating_arr), ".2f"))
print("25th Percentile:", format(np.percentile(rating_arr, 25), ".2f"))
print("75th Percentile:", format(np.percentile(rating_arr, 75), ".2f"))

TOTAL STATISTICS
Mean: 322.97
Median: 253.85
Standard Deviation: 245.76
Minimum: 10.68
Maximum: 1042.65
25th Percentile: 124.42
75th Percentile: 471.35

RATING STATISTICS
Mean: 6.97
Median: 7.00
Standard Deviation: 1.72
Minimum: 4.00
Maximum: 10.00
25th Percentile: 5.50
75th Percentile: 8.50


QUESTION 6:

Answer the following using NumPy array operations:
a) Create a new array called revenue_arr by multiplying unit_price_arr by quantity_arr.
Compare its first 5 values to the first 5 values of total_arr. Are they the same? Explain your
observation in a Markdown cell.
b) Create a new array called satisfaction where each element is the label "Happy" if the
rating is 7 or above, "Neutral" if it is 5 or above, and "Unhappy" otherwise. Print the
count of each label.
c) Compute the correlation between total_arr and rating_arr. Print the result and write a
Markdown cell explaining what the number tells you about the relationship between how
much a customer spends and how satisfied they are.

In [5]:
# Create revenue array
revenue_arr = unit_price * quantity_arr

# Print first 5 values
print("Revenue (first 5):")
print(revenue_arr[:5])

print("Total (first 5):")
print(total_arr[:5])
# B
satisfaction = np.where(
    rating_arr >= 7,
    "Happy",
    np.where(rating_arr >= 5, "Neutral", "Unhappy")
)

# C
correlation = np.corrcoef(total_arr, rating_arr)

print(correlation)

Revenue (first 5):
[522.83  76.4  324.31 465.76 604.17]
Total (first 5):
[548.9715  80.22   340.5255 489.048  634.3785]
[[ 1.        -0.0364417]
 [-0.0364417  1.       ]]


QUESTION 7:

Load the dataset using Pandas and carry out an initial inspection. Answer the following:
a) What is the shape of the dataset? How many rows and columns does it have?
b) What is the data type of each column? Print a list of column names alongside their data
types.
c) Print the first 5 rows and the last 5 rows.
d) Generate summary statistics for all numeric columns. In a Markdown cell, state which
column has the highest mean value and what the average customer rating is.

In [6]:
import pandas as pd

# Load dataset
sales = pd.read_csv("supermarket_sales - Sheet1.csv")

# (a)
print("Shape:", sales.shape)

# (b)
for column in sales.columns:
    print(column, ":", sales[column].dtype)

# (c)
print("\nFirst 5 Rows")
print(sales.head())

print("\nLast 5 Rows")
print(sales.tail())

# (d)
summary = sales.describe()

print(summary)

Shape: (1000, 17)
Invoice ID : object
Branch : object
City : object
Customer type : object
Gender : object
Product line : object
Unit price : float64
Quantity : int64
Tax 5% : float64
Total : float64
Date : object
Time : object
Payment : object
cogs : float64
gross margin percentage : float64
gross income : float64
Rating : float64

First 5 Rows
    Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428      A     Yangon        Member  Female   
1  226-31-3081      C  Naypyitaw        Normal  Female   
2  631-41-3108      A     Yangon        Normal    Male   
3  123-19-1176      A     Yangon        Member    Male   
4  373-73-7910      A     Yangon        Normal    Male   

             Product line  Unit price  Quantity   Tax 5%     Total       Date  \
0       Health and beauty       74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories       15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle       46.33         7  16.2155  34

QUESTION 8:

Select and retrieve specific parts of the DataFrame.
a) Select only the Unit price, Quantity, and Total columns. Print the shape of the result.
b) Using integer-based indexing, select rows 5 to 15 and the first 4 columns. Print the result.
c) Using label-based indexing, find and print the Branch, Product line, and Total value of the
transaction that has the highest Total in the dataset.
d) Select only the numeric columns and print how many there are. Then select only the text
columns and print their names.

In [7]:
# (a)
selected = sales[["Unit price","Quantity","Total"]]

print(selected)
print(selected.shape)

# (b)
print(sales.iloc[5:16,0:4])

# (c)
highest = sales["Total"].idxmax()

print(sales.loc[highest,["Branch","Product line","Total"]])

# (d)
numeric = sales.select_dtypes(include="number")

print("Number of numeric columns:",numeric.shape[1])

text = sales.select_dtypes(include="object")

print("Text columns:")
print(list(text.columns))

     Unit price  Quantity      Total
0         74.69         7   548.9715
1         15.28         5    80.2200
2         46.33         7   340.5255
3         58.22         8   489.0480
4         86.31         7   634.3785
..          ...       ...        ...
995       40.35         1    42.3675
996       97.38        10  1022.4900
997       31.84         1    33.4320
998       65.82         1    69.1110
999       88.34         7   649.2990

[1000 rows x 3 columns]
(1000, 3)
     Invoice ID Branch       City Customer type
5   699-14-3026      C  Naypyitaw        Normal
6   355-53-5943      A     Yangon        Member
7   315-22-5665      C  Naypyitaw        Normal
8   665-32-9167      A     Yangon        Member
9   692-92-5582      B   Mandalay        Member
10  351-62-0822      B   Mandalay        Member
11  529-56-3974      B   Mandalay        Member
12  365-64-0515      A     Yangon        Normal
13  252-56-2699      A     Yangon        Normal
14  829-34-3910      A     Yangon        

QUESTION 9

Filter the dataset to answer the following questions. For each one, print the number of rows
returned and the first 3 rows of the result.
a) Which transactions were made at Branch A?
b) Which transactions had a Total greater than 500?
c) Which transactions were made by Female customers who paid by Ewallet?
d) Which transactions had a Rating between 8 and 10 inclusive?
e) Which transactions were made at Branch B or Branch C?
f) Which transactions had a Quantity of 5 or more and a Unit price above 50?

In [8]:
# (a)
branch_a = sales[sales["Branch"] == "A"]

print("Number of rows:", branch_a.shape[0])
print(branch_a.head(3))


# (b)
total_500 = sales[sales["Total"] > 500]

print("Number of rows:", total_500.shape[0])
print(total_500.head(3))


# (c)
female_ewallet = sales[
    (sales["Gender"] == "Female") &
    (sales["Payment"] == "Ewallet")
]

print("Number of rows:", female_ewallet.shape[0])
print(female_ewallet.head(3))


# (d)
rating = sales[sales["Rating"].between(8,10)]

print("Number of rows:", rating.shape[0])
print(rating.head(3))


# (e)
branch_bc = sales[
    sales["Branch"].isin(["B","C"])
]

print("Number of rows:", branch_bc.shape[0])
print(branch_bc.head(3))


# (f)
quantity_price = sales[
    (sales["Quantity"] >= 5) &
    (sales["Unit price"] > 50)
]

print("Number of rows:", quantity_price.shape[0])
print(quantity_price.head(3))

Number of rows: 340
    Invoice ID Branch    City Customer type  Gender        Product line  \
0  750-67-8428      A  Yangon        Member  Female   Health and beauty   
2  631-41-3108      A  Yangon        Normal    Male  Home and lifestyle   
3  123-19-1176      A  Yangon        Member    Male   Health and beauty   

   Unit price  Quantity   Tax 5%     Total       Date   Time      Payment  \
0       74.69         7  26.1415  548.9715   1/5/2019  13:08      Ewallet   
2       46.33         7  16.2155  340.5255   3/3/2019  13:23  Credit card   
3       58.22         8  23.2880  489.0480  1/27/2019  20:33      Ewallet   

     cogs  gross margin percentage  gross income  Rating  
0  522.83                 4.761905       26.1415     9.1  
2  324.31                 4.761905       16.2155     7.4  
3  465.76                 4.761905       23.2880     8.4  
Number of rows: 227
    Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428      A     Yangon        Member  Female  

QUESTION 10:

Add the following four new columns to the DataFrame. Print the first 3 rows after all columns
have been added.
a) revenue : calculated as Unit price multiplied by Quantity.
    
b) is_member : True if the Customer type is Member, False otherwise.
    
c) high_value : True if the Total is greater than 500, False otherwise.
    
d) rating_label : the value Excellent if the Rating is 8 or above, Good if it is 6 or above, and
Poor otherwise.
After adding all four columns, print how many transactions are marked as high-value and show
the count of each rating label.

In [9]:
import numpy as np

# (a)
sales["revenue"] = sales["Unit price"] * sales["Quantity"]

# (b)
sales["is_member"] = sales["Customer type"] == "Member"

# (c)
sales["high_value"] = sales["Total"] > 500

# (d)
sales["rating_label"] = np.where(
    sales["Rating"] >= 8,
    "Excellent",
    np.where(
        sales["Rating"] >= 6,
        "Good",
        "Poor"
    )
)

# Print first 3 rows
print(sales.head(3))

# Number of high value transactions
print("High Value Transactions:", sales["high_value"].sum())

# Count each rating label
print(sales["rating_label"].value_counts())

    Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428      A     Yangon        Member  Female   
1  226-31-3081      C  Naypyitaw        Normal  Female   
2  631-41-3108      A     Yangon        Normal    Male   

             Product line  Unit price  Quantity   Tax 5%     Total  ...  \
0       Health and beauty       74.69         7  26.1415  548.9715  ...   
1  Electronic accessories       15.28         5   3.8200   80.2200  ...   
2      Home and lifestyle       46.33         7  16.2155  340.5255  ...   

    Time      Payment    cogs  gross margin percentage  gross income  Rating  \
0  13:08      Ewallet  522.83                 4.761905       26.1415     9.1   
1  10:29         Cash   76.40                 4.761905        3.8200     9.6   
2  13:23  Credit card  324.31                 4.761905       16.2155     7.4   

   revenue  is_member  high_value  rating_label  
0   522.83       True        True     Excellent  
1    76.40      False       False     Excelle